### ISSUE TITLE
Add config subsystem

### ISSUE THREAD

**Issue by jvalkeal** [rd-1-2022/spring-up#2]
We need to store authentication tokes for various
git repos, github/gitlab being basic ones.

Need to create a system which stores these on a local file
system as a yaml files. Should be a separate config files
which commands can read/write.

**Comment by markpollack** [comment]
Having config files under the user's home directory with a main config file such as `~/.springup/config.toml`  (or yaml) would be a good starting point.  I've been quite inspired by the choices made by the rust ecosystem in various areas so take a look at https://doc.rust-lang.org/cargo/reference/config.html for larger set of config system options.  Probably overkill for now, but should discuss it more.

**Comment by jvalkeal** [comment]
I did go though various things how config files are used in a java space and story is that it's mostly server side and read-only. Basically no existing solution for a client side where cli write/read opinionated configs.

It looks like solution is to simply do generic yaml read/write with wrapped knowledge of OS specific base user dirs. This simple pojo mapping to yaml allows to handle complex structures simple using different files. This is what gh cli do and it's simple(thought done in go).
